version: '3.8'

services:
  mapper2sql-mcp:
    build: .
    container_name: mapper2sql-mcp-server
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
    volumes:
      # 挂载mapper文件目录
      - ./mapper-files:/app/mapper-files:ro
      # 挂载输出目录
      - ./output:/app/output
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "java", "-jar", "app.jar", "--health"]
      interval: 30s
      timeout: 10s
      retries: 3
