CREATE TABLE users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    create_time DATETIME NOT NULL,
    status INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;